[supervisord]
nodaemon = true
logfile = /var/lib/pylai/log/supervisord.log
logfile_maxbytes = 0
loglevel = error
pidfile = /run/supervisord.pid
user = root

[program:backend]
command = /opt/pylai/Pylaios serve --config /var/lib/pylai/pylai.toml
directory = /opt/pylai
user = pylai
autorestart = true
environment = ASPNETCORE_ENVIRONMENT="Production",HOME="/var/lib/pylai"
stdout_logfile = /dev/fd/1
stdout_logfile_maxbytes = 0
stdout_logfile_backups = 0
stderr_logfile = /dev/fd/2
stderr_logfile_maxbytes = 0
stderr_logfile_backups = 0

[program:redis]
command = redis-server /var/lib/pylai/redis.conf
user = redis
autorestart = true
stdout_logfile = /dev/fd/1
stdout_logfile_maxbytes = 0
stdout_logfile_backups = 0
stderr_logfile = /dev/fd/2
stderr_logfile_maxbytes = 0
stderr_logfile_backups = 0

[program:nginx]
command = /bin/sh -c 'exec /usr/sbin/nginx -c /etc/nginx/sites-available/pylai-server -g "daemon off;" 2>/dev/null'
user = root
autorestart = true
stdout_logfile = /dev/null
stderr_logfile = /dev/null
